[training_loop]
epochs = 50
batch_size = 16
number_of_workers = 10
learning_rate = 7.0e-04
momentum = 1.0e-01
weight_decay = 1.0e-02
display = true

[data_set]
training_data_root = "data/PASCAL_VOC"
train_file_name = "train.csv"
test_file_name = "test.csv"
class_names = "class-names.csv"
image_directory_name = "images"
lable_directory_name = "labels"
image_width = 216
image_height = 216
number_of_detections = 5

[yolo_model]
input_channel = 3
num_classes = 20
num_anchors = 3
layers_structure = [ [ 32, 3, 1, 0 ], [ 64, 3, 2, 2 ], [ 128, 3, 2, 4 ], [ 256, 3, 2, 8 ], [ 512, 3, 2, 16 ], [ 1024, 3, 2, 16 ] ]
model_path = "saved_models/69"
model_weight_file_name = "yolv3.pt"
model_optimize_file_name = "opitimize.pt"
model_weight_file_name_current = "yolov3_current.pt"
model_loss_graph_file = "loss.png"
model_loss_graph_file_current = "loss_current.png"

[camera]
image_width = 640
image_height = 480

[inference]
bojectness_threshold = 0.51
class_threshold = 0.51