[training_loop]
epochs = 100
batch_size = 15
number_of_workers = 10
learning_rate = 1.0e-04
momentum = 1.0e-1
weight_decay = 1.0e-04
display = true

[data_set]
training_data_root = "data/PASCAL_VOC"
train_file_name = "train.csv"
test_file_name = "test.csv"
class_names = "class-names.csv"
image_directory_name = "images"
lable_directory_name = "labels"
image_width = 216
image_height = 216
number_of_detections = 5

[yolo_model]
input_channel = 3
num_classes = 20
num_anchors = 3
layers_structure = [ [ 32, 3, 1, 0 ], [ 64, 3, 2, 1 ], [ 128, 3, 2, 2 ], [ 256, 3, 2, 8 ], [ 512, 3, 2, 8 ], [ 1024, 3, 2, 4 ] ]
model_path = "saved_models/28"
model_weight_file_name = "yolv3.pt"
model_weight_file_name_current = "yolov3_current.pt"
model_loss_graph_file = "loss.png"
model_loss_graph_file_current = "loss_current.png"

[camera]
image_width = 640
image_height = 480

[inference]
bojectness_threshold = 0.8
class_threshold = 0.8